-- DRIVE ANGO — ANALYTICS / ADM ONLINE / UTILIZADORES
-- Executar DEPOIS do supabase-schema.sql

create table if not exists public.login_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);
alter table public.login_events enable row level security;
drop policy if exists "Users can record own login" on public.login_events;
create policy "Users can record own login" on public.login_events
for insert to authenticated with check (auth.uid()=user_id);
drop policy if exists "Admins can read login events" on public.login_events;
create policy "Admins can read login events" on public.login_events
for select to authenticated using (public.is_current_user_admin());
create index if not exists login_events_user_created_idx on public.login_events(user_id,created_at desc);

create table if not exists public.admin_presence (
  user_id uuid primary key references auth.users(id) on delete cascade,
  last_seen_at timestamptz not null default now()
);
alter table public.admin_presence enable row level security;
drop policy if exists "Admins can read admin presence" on public.admin_presence;
create policy "Admins can read admin presence" on public.admin_presence
for select to authenticated using (public.is_current_user_admin());
drop policy if exists "Admins can upsert own presence" on public.admin_presence;
create policy "Admins can upsert own presence" on public.admin_presence
for insert to authenticated with check (auth.uid()=user_id and public.is_current_user_admin());
drop policy if exists "Admins can update own presence" on public.admin_presence;
create policy "Admins can update own presence" on public.admin_presence
for update to authenticated using (auth.uid()=user_id and public.is_current_user_admin()) with check (auth.uid()=user_id and public.is_current_user_admin());
create index if not exists admin_presence_seen_idx on public.admin_presence(last_seen_at desc);

-- Remover presença antiga automaticamente quando um administrador deixa de estar ativo.
