const params=new URLSearchParams(location.search), id=params.get('id');let car=null;
const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function money(v){return Number(v||0).toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});}
function show(msg,type='notice'){const box=$('message');if(box){box.className=type;box.textContent=msg;box.classList.remove('hidden');box.scrollIntoView({behavior:'smooth',block:'center'});}}
async function init(){
 if(!window.driveSupabase||!window.driveCarsData){show('Serviço de compra indisponível.','error');return;}
 const {data:{user}}=await window.driveSupabase.auth.getUser();
 if(!user){show('Para enviar um pedido de compra, inicia sessão primeiro. Depois volta a clicar em BUY NOW.','notice');return;}
 const {data,error}=await window.driveCarsData.fetchCars({publicOnly:true}); if(error){show('Não foi possível carregar o veículo.','error');return;}
 car=(data||[]).find(c=>c.id===id); if(!car){show('Este anúncio não está disponível.','error');return;}
 const img=car.image||car.images?.[0]||'';
 $('buyApp').innerHTML=`<div id="message" class="hidden"></div><div class="buy-grid"><section class="card vehicle"><img src="${esc(img)}" alt="${esc(car.brand)} ${esc(car.model)}"><h1>${esc(car.brand)} ${esc(car.model)}</h1><div>${esc(car.year)} · ${esc(car.body||'')}</div><div class="price">${money(car.price)}</div><div class="stock">Stock: ${esc(car.stock||car.id)}</div><div class="specs">${[['Cor',car.color],['Localização',car.location],['Direção',car.drive||car.wheel],['Combustível',car.fuel],['Assentos',car.seats],['Portas',car.doors],['Dimensão',car.dimensions],['Motor',car.engine],['Câmbio',car.trans]].map(x=>`<div class="spec"><small>${x[0]}</small><b>${esc(x[1]||'—')}</b></div>`).join('')}</div></section><section class="card"><h2>Pedido de compra</h2><div class="form-grid"><div class="field"><label>Nome</label><input id="buyerName" value="${esc(user.user_metadata?.name||'')}" required></div><div class="field"><label>Telefone / WhatsApp</label><input id="buyerPhone" value="${esc(user.user_metadata?.phone||'')}" required></div><div class="field"><label>País final</label><input id="country" value="Moçambique"></div><div class="field"><label>Cidade / Porto</label><input id="port" value="Maputo"></div><div class="field"><label>Método de envio</label><select id="shipping"><option>RORO</option><option>Container</option></select></div><div class="field full"><label>Método de pagamento</label><div class="payment-options"><label class="payment-option"><input type="radio" name="payment" value="Transferência bancária" checked><span><i class="fa-solid fa-building-columns"></i> Transferência bancária</span></label><label class="payment-option"><input type="radio" name="payment" value="Cartão"><span><i class="fa-solid fa-credit-card"></i> Cartão</span></label><label class="payment-option paypal-option"><input type="radio" name="payment" value="PayPal"><span><i class="fa-brands fa-paypal"></i> PayPal</span></label></div></div><div class="field"><label>Seguro marítimo</label><select id="insurance"><option>Sim</option><option>Não</option></select></div><div class="field"><label>Inspeção</label><select id="inspection"><option>Sim</option><option>Não</option></select></div><div class="field"><label>Garantia</label><select id="warranty"><option>Sim</option><option>Não</option></select></div><div class="field"><label>Cupom de desconto</label><input id="coupon" placeholder="Opcional"></div><div class="field full"><label>Observações</label><textarea id="notes" placeholder="Escreva alguma informação adicional..."></textarea></div></div><div class="summary">Veículo: <b>${esc(car.brand)} ${esc(car.model)}</b><br>Preço: <b>${money(car.price)}</b></div><button id="submit" class="submit" type="button"><i class="fa-solid fa-cart-shopping"></i> CONFIRMAR PEDIDO DE COMPRA</button></section></div>`;
 $('submit').onclick=submitOrder;
}
async function submitOrder(){const b=$('submit');b.disabled=true;b.textContent='A enviar pedido...';try{const {data:{user}}=await window.driveSupabase.auth.getUser();if(!user)throw new Error('A sessão terminou. Entra novamente.');const payload={car_id:car.id,customer_id:user.id,customer_name:$('buyerName').value.trim(),customer_email:user.email||'',customer_phone:$('buyerPhone').value.trim(),country:$('country').value.trim(),destination:$('port').value.trim(),shipping_method:$('shipping').value,payment_method:document.querySelector('input[name=\"payment\"]:checked')?.value||'Transferência bancária',insurance:$('insurance').value,inspection:$('inspection').value,warranty:$('warranty').value,coupon:$('coupon').value.trim(),notes:$('notes').value.trim(),vehicle_snapshot:{brand:car.brand,model:car.model,year:car.year,stock:car.stock||car.id,price:car.price,image:car.image||car.images?.[0]||''}};const {error}=await window.driveSupabase.from('purchase_orders').insert(payload);if(error)throw error;show('Pedido enviado com sucesso. Os Proprietários Principais foram notificados.','success');b.textContent='Pedido enviado ✓';}catch(e){console.error(e);show('Não foi possível enviar o pedido: '+(e.message||'erro desconhecido'),'error');b.disabled=false;b.textContent='CONFIRMAR PEDIDO DE COMPRA';}}
document.addEventListener('DOMContentLoaded',init);
