const id=new URLSearchParams(location.search).get("id");
const cars=JSON.parse(localStorage.getItem("driveCars")||"[]");
const fallback=[{id:"DRV001",brand:"Toyota",model:"RAV4",body:"SUV",price:18500,year:2022,km:23500,engine:"2,000cc",trans:"AT",drive:"4WD",wheel:"RHD",image:"https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1200&q=80",status:"available"}];
const car=cars.find(x=>x.id===id)||(cars[0]||fallback[0]);
const contact=localStorage.getItem("driveContact")||"";
const phone=contact.replace(/\D/g,"");
function status(){if(car.status==="sold")return '<span class="detail-status sold">VENDIDO</span>';if(car.status==="reserved")return `<span class="detail-status reserved">RESERVADO — ${countdown(car.reservedUntil)}</span>`;return '<span class="detail-status available">DISPONÍVEL</span>';}
function countdown(until){if(!until)return "48:00:00";let s=Math.max(0,Math.floor((Number(until)-Date.now())/1000));return [Math.floor(s/3600),Math.floor(s%3600/60),s%60].map(x=>String(x).padStart(2,"0")).join(":");}
function wa(){if(!phone)return "#";return `https://wa.me/${phone}?text=${encodeURIComponent(`Olá, tenho interesse no ${car.brand} ${car.model} (${car.id}).`)}`;}
function call(){return phone?`tel:+${phone}`:"#";}
document.getElementById("detail").innerHTML=`<div class="gallery"><img src="${car.image}" alt="${car.brand} ${car.model}"></div><div class="info"><div>${status()}</div><small>${car.year} · ${car.brand} · Stock ${car.id}</small><h1>${car.model}</h1><div class="price">USD ${Number(car.price).toLocaleString()}</div>${car.discount?`<p class="discount">-${car.discount}% de desconto</p>`:""}<div class="specs"><div>KM<br><b>${Number(car.km).toLocaleString()}</b></div><div>Motor<br><b>${car.engine||"—"}</b></div><div>Transmissão<br><b>${car.trans||"—"}</b></div><div>Tração<br><b>${car.drive||"—"}</b></div><div>Volante<br><b>${car.wheel||"—"}</b></div><div>Ano<br><b>${car.year}</b></div></div><div class="detail-actions"><a class="cta" href="${car.status==='available'?wa():'#'}" target="_blank" onclick="${car.status==='available'?'':'return false;'}"><i class="fa-brands fa-whatsapp"></i> WhatsApp</a><a class="cta secondary-cta" href="${car.status==='available'?call():'#'}" onclick="${car.status==='available'?'':'return false;'}"><i class="fa-solid fa-phone"></i> Ligar</a></div></div>`;
if(car.status==="reserved"){setInterval(()=>{const el=document.querySelector(".detail-status");if(el)el.textContent=`RESERVADO — ${countdown(car.reservedUntil)}`;},1000);}
