-- DRIVE CARS — SQL CONSOLIDADO V4.2
-- Este ficheiro foi consolidado no supabase-schema.sql V4.2.
-- NÃO executar separadamente: uma versão antiga deste script recriava uma
-- policy pública que permitia ler anúncios published=false.
-- Execute apenas: supabase-schema.sql
